default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: 127.0.0.1

development:
  primary:   # MySQL 8.0.43
    <<: *default
    database: prontooss
    username: adminuser
    password: "Root@123"
    port: 3306

  legacy:    # MySQL 5.7
    <<: *default
    database: prontooss
    username: legacy_user
    password: Root@123
    host: 127.0.0.1
    port: 3307
    # Prevent Rails from trying to run migrations/checks against this DB in dev
    database_tasks: false
    migrations_paths: []

test:
  primary:
    <<: *default
    database: prontooss_test
    username: adminuser
    password: "Root@123"
    port: 3306

production:
  primary:
    <<: *default
    database: prontooss_prod
    username: adminuser
    password: "Root@123"
    port: 3306
