:concurrency: 5
:queues:
  - default
  - critical
:scheduler:
  enabled: true
  schedule:
    # rca_detector_job:
    #   every: ["5s"]
    #   class: "RcaDetectorJob"
    alert_dispatcher_job:
      every: ["2s"]
      class: "AlertDispatcherJob"
