:concurrency: 5
:queues:
  - default
  - critical
:scheduler:
  enabled: true
  schedule:
    rca_detector_job:
      every: ["1m"]   # every 5 minutes
      class: "RcaDetectorJob"
    alert_dispatcher_job:
      every: ["1m"]   # every 2 minutes
      class: "AlertDispatcherJob"
